# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_roll', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=60)),
                ('topic', models.CharField(max_length=255)),
                ('std_teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Teacher')),
            ],
        ),
    ]
