# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160801_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_roll', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=60)),
                ('topic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='std_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Teacher'),
        ),
    ]
