# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermeet',
            name='meet_teacher_id',
        ),
    ]
