# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 11:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_teachermeet_meet_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='marks',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='teacher_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
